#!/bin/bash
set -e

#       PROJECT: stackfor
#      FILENAME: filezilla
#         BUILD: 170907
#   DESCRIPTION: Installs FileZilla.
#       AUTHORS: Christopher Banwarth (development@aprettycoolprogram.com)
#     COPYRIGHT: 2017 A Pretty Cool Program
#       LICENSE: Apache License, Version 2.0 [http://www.apache.org/licenses/LICENSE-2.0]
#     MORE INFO: http://aprettycoolprogram.com/stackfor

source "$stackforBin/stackfor"

InstallPrereqs() {
    prereqs="none"
}

InstallFileZilla() {
    InstallPackageMinimal filezilla
}

## MAIN
InstallPrereqs
InstallFileZilla