#!/bin/bash
set -e

#       PROJECT: stackfor
#      FILENAME: ide
#         BUILD: 170907
#   DESCRIPTION: Install and IDE.
#       AUTHORS: Christopher Banwarth (development@aprettycoolprogram.com)
#     COPYRIGHT: 2017 A Pretty Cool Program
#       LICENSE: Apache License, Version 2.0 [http://www.apache.org/licenses/LICENSE-2.0]
#     MORE INFO: http://aprettycoolprogram.com/stackfor


InstallPrereqs() {
    InstallPackage curl \
                   apt-transport-https
}

InstallEmacs() {
    InstallPackageMinimal emacs
}

InstallCode() {
    if [[ ! -f $stackforHistory/code.repository ]]; then
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
        touch $stackforHistory/code.repository
    fi | tee -a $stackforLogs/code.repository
    InstallPackage code
}

## MAIN

InstallPrereqs

if [[ $1 == "--just-emacs"]]; then
    InstallEmacs
elif [[ $1 == "--just-code"]]; then
    InstallCode
else
    InstallEmacs
    InstallCode
fi