#!/bin/bash
set -e

#       PROJECT: stackfor
#      FILENAME: xfce4
#         BUILD: 170907
#   DESCRIPTION: Adds a GUI (XFCE4) to your environment
#       AUTHORS: Christopher Banwarth (development@aprettycoolprogram.com)
#     COPYRIGHT: 2017 A Pretty Cool Program
#       LICENSE: Apache License, Version 2.0 [http://www.apache.org/licenses/LICENSE-2.0]
#     MORE INFO: http://aprettycoolprogram.com/stackfor

source "$stackforBin/stackfor"

InstallPackage xorg
InstallPackageMinimal xfce4
InstallPackage tango-icon-theme \
               xfce4-terminal